#!/bin/bash

while true; do
  dwm-clock;
  sleep 1m;
done &

xmodmap -e "remove lock = Caps_Lock";

##Java fix
_JAVA_AWT_WM_NONREPARENTING=1;
export _JAVA_AWT_WM_NONREPARENTING;

## Wallpaper
#feh --bg-scale '/home/gedas/Pictures/Wallpapers/371401.jpg';
